api:
  bc_crypto_coingecko:
    domain: localhost:8082/crypto/coingecko/api/v1
    endpoints:
      currency: usd
      ids: bitcoin,ethereum
  bc_stock_finnhub:
    domain: localhost:8083/stock/finnhub/api/v1/getStock
    symbols: AAPL,MSFT,NVDA


  #MySQL Config
spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/bc2311project
  username: oscarlo
  password: oscarVenturenixLab2023.
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # create-drop
spring.sql.init:
  mode: always # always
  platform: mysql
spring.profiles.active: enableScheduling
