api:
  bc_crypto_coingecko:
    domain: localhost:8082/crypto/coingecko/api/v1
    endpoints:
      currency: usd
      ids: bitcoin,ethereum
  bc_stock_finnhub:
    domain: localhost:8083/stock/finnhub/api/v1/
    endpoint:
      quote: quote
      profile: profile2
      stock: getStock
    symbols: AAPL,MSFT,NVDA

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bc2311
    username: "postgres"
    password: "admin1234"
    driver-class-name: "org.postgresql.Driver"
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # create-drop
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      default_schema: bc2311
      jdbc:
        time_zone: UTC
